framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:      
        cookie_secure: auto
        cookie_samesite: lax
        # enables the support of sessions in the app
        enabled: true
        # ID of the service used for session storage.
        # NULL =  means that PHP's default session mechanism is used
        handler_id: null       

    #esi: true
    #fragments: true
    php_errors:
        log: true
